# Generated by Django 4.1.7 on 2023-03-28 18:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuarios_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='prestador',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Postagens',
            fields=[
                ('id_Postagem', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensagem', models.CharField(max_length=255)),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
        ),
    ]
