# Generated by Django 4.1.7 on 2023-03-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cep',
            field=models.IntegerField(),
        ),
    ]
